### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by ValarDragon** [LiquidLemon/CTF-Bot#1]
Could you add a way to list the username / passwords for active ctfs?
Like right now there are 3 ctfs going on, it would be nice if there was a way to get all logins (if set ofc), since only one login goes in the motd/title of the irc channel.

**Comment by LiquidLemon** [comment]
That would be an useful feature. I'll get on it.

**Comment by LiquidLemon** [comment]
Feature has been added.
